### PR TITLE
[Test] Add unit test for validator Router connections

### LINKED ISSUE #3196: [Bug] Peers are not sufficiently connecting to each other
## 🐛 Bug Report

It seems that our nodes are not connected as optimally as we'd like. Perhaps existing PRs ([link](https://github.com/AleoHQ/snarkOS/pull/3164)) will improve the situation

## Steps to Reproduce

Set up a network with 10 validators and 100 clients. The 10 validators should connect to each other, and each validator should connect to 10 trusted peers using `--peers`. We would prefer `snarkos_router_connected_total` to approach 19, but it is only 8.

In contrast, a local default `devnet.sh` run does reveal `N-1` validators are connected via `snarkos_router_connected_total`.

## Your Environment

SnarkOS commit `491f3078a`.

### PR DESCRIPTION
**Pull request by vicsn**
## Motivation

Due to the recently introduced `--allow-external-peers` flag, validator Routers do not by default accept connections from other validator Routers. We noticed on tests with only validators that the `snarkos_router_connected_total` metric returned 0.

To make this behavior clear, added a unit test `test_validator_connection`. In order for validator's Routers to connect to one another, their address has to be explicitly passed via `--peers`.

Note that if we want to change that behaviour, we need to either:
- add Gateway features to Router (e.g. a `Resolver` to track whether we are not connected to the same address twice)
- do a bigger refactor to merge Gateway and Router so the validator has just one TCP stack

## Related PRs

Closes https://github.com/AleoHQ/snarkOS/issues/3196
Corrects yet another regression from https://github.com/AleoHQ/snarkOS/pull/3163
Improves on https://github.com/AleoHQ/snarkOS/pull/3192

### CODE REVIEW

File: node/router/src/handshake.rs [hunk 1]
```diff
@@ -251,7 +252,7 @@ impl<N: Network> Router<N> {
     }
 
     /// Ensure the peer is allowed to connect.
-    fn ensure_peer_is_allowed(&self, peer_ip: SocketAddr) -> Result<()> {
+    fn ensure_peer_is_allowed(&self, peer_ip: SocketAddr, node_type: NodeType) -> Result<()> {
```
Comment (niklaslong) [inline node/router/src/handshake.rs]: Note that we have to trust the node type as it's given to us by the peer, I don't think we previously used it for anything so we're introducing a new assumption.

File: node/router/tests/connect.rs [hunk 2]
```diff
@@ -150,11 +150,48 @@ async fn test_connect_with_handshake() {
...
+
+    // Start listening.
+    node0.tcp().enable_listener().await.unwrap();
+    node1.tcp().enable_listener().await.unwrap();
+
+    {
+        // Connect node0 to node1.
+        node0.connect(node1.local_ip());
+        // Sleep briefly.
+        tokio::time::sleep(Duration::from_millis(200)).await;
```
Comment (niklaslong) [inline node/router/tests/connect.rs:174]: `deadline` could be used here to avoid the `sleep`.

File: node/router/src/handshake.rs (hunk 1 above)
Comment (vicsn) [reply node/router/src/handshake.rs]: You are right. The easiest immediate resolution is to pass in validator routers explicitly via `--peers`. I added a unit test for it and updated the PR description. 297461215

File: node/router/tests/connect.rs (hunk 2 above)
Comment (vicsn) [reply node/router/tests/connect.rs:174]: Will keep it in mind for future tests, for now I'll keep the logic similar to the rest of the tests in the file.

Comment (ljedrz) [reply node/router/tests/connect.rs:174]: IIRC `connect` returns a `JoinHandle` that can be `.await`ed (and once it's complete, it means the connection is either ready or that it has failed), so there is no need for a `sleep` here

File: node/router/tests/connect.rs [hunk 3]
```diff
@@ -150,11 +150,64 @@ async fn test_connect_with_handshake() {
...
+        assert_eq!(node1.number_of_connected_peers(), 1);
+
+        // Disconnect the nodes.
+        node0.disconnect(node1.local_ip());
+        node1.disconnect(node0.local_ip());
+
+        // Connect node1 to node0.
+        node1.connect(node0.local_ip());
+        // Sleep briefly.
+        tokio::time::sleep(Duration::from_millis(200)).await;
```
Comment (ljedrz) [inline node/router/tests/connect.rs:194]: ditto

File: node/router/tests/connect.rs [hunk 4]
```diff
@@ -150,11 +150,64 @@ async fn test_connect_with_handshake() {
...
+
+    // Create second router, trusting the first router, and start listening.
+    let node1 = validator(0, 2, &[addr0], false).await;
+    assert_eq!(node1.number_of_connected_peers(), 0);
+    node1.enable_handshake().await;
+    node1.tcp().enable_listener().await.unwrap();
+
+    {
+        // Connect node0 to node1.
+        node0.connect(node1.local_ip());
```
Comment (ljedrz) [inline node/router/tests/connect.rs:172]: aren't we racing against the `Heartbeat` (that might cause `node1` to attempt to connect to `node0`) here? then again, that direction should fail, so it's probably fine

**Review by ljedrz — COMMENTED** [review]
LGTM with some nits addressed.

File: node/router/tests/connect.rs (hunk 2 above)
Comment (vicsn) [reply node/router/tests/connect.rs:174]: Just tried it. Just awaiting node0's connect is not enough, because node1 might not be connected yet. I suggest we leave refactoring this file for later.

File: node/router/tests/connect.rs (hunk 4 above)
Comment (vicsn) [reply node/router/tests/connect.rs:172]: heartbeat is not turned on, only if we call `initialize_routing`.

File: node/router/tests/connect.rs (hunk 3 above)
Comment (vicsn) [reply node/router/tests/connect.rs:194]: ditto comment above

**Review by howardwu — APPROVED** [review]
