### PR TITLE
Reduce stale transmissions

### LINKED ISSUE #3514: [Bug] Fix faulty STALE_UNCONFIRMED_TRANSMISSIONS metric
## 🐛 Bug Report

In both canary and mainnet, `STALE_UNCONFIRMED_TRANSMISSIONS` is around 10% of total transactions, which seems like a lot.

This is because we start tracking transmissions before we observe whether we've already seen them before.

### PR DESCRIPTION
**Pull request by vicsn**
## Motivation

Closes https://github.com/ProvableHQ/snarkOS/issues/3514

Also fixes a potential bug introduced by https://github.com/ProvableHQ/snarkOS/pull/3471 where transmissions surpassing `MAX_TRANSMISSIONS_PER_BATCH` or `MAX_TRANSMISSIONS_PER_WORKER` may be dropped needlessly.

## Test Plan

- [x] Run test network and observe stale transmissions - https://aleostresstest.grafana.net/d/single-region-tests-kp/single-region-tests-kp?from=2025-06-23T14:59:52.748Z&to=2025-06-23T16:48:31.155Z&refresh=5s&timezone=browser&orgId=1

### CODE REVIEW

**Comment by niklaslong** [comment]
Good catch on the #3471 bug!

File: node/consensus/src/lib.rs [hunk 1]
```diff
@@ -392,10 +390,10 @@ impl<N: Network> Consensus<N> {
             } else if self.transactions_queue.lock().executions.put(transaction_id, transaction).is_some() {
                 bail!("Transaction '{}' exists in the memory pool", fmt_id(transaction_id));
             }
-
-            // Try to process the unconfirmed transactions in the memory pool.
-            self.process_unconfirmed_transactions().await
         }
+
+        // Try to process the unconfirmed transactions in the memory pool.
+        self.process_unconfirmed_transactions().await
```
Comment (niklaslong) [inline node/consensus/src/lib.rs:396]: Was this moved out of the scope for readability?

**Review by niklaslong — APPROVED** [review]

File: node/consensus/src/lib.rs (hunk 1 above)
Comment (vicsn) [reply node/consensus/src/lib.rs:396]: Yes, just to be more consistent with the similar `solutions` function and the comment `// Queue the unconfirmed transaction.` Not sure why the scope is there in the first place 🤷 🦐

File: node/consensus/src/lib.rs [hunk 2]
```diff
@@ -111,8 +111,8 @@ pub struct Consensus<N: Network> {
     /// The recently-seen unconfirmed transactions.
     seen_transactions: Arc<Mutex<LruCache<N::TransactionID, ()>>>,
     #[cfg(feature = "metrics")]
-    transmissions_queue_timestamps: Arc<Mutex<HashMap<TransmissionID<N>, i64>>>,
-    /// The handles of all spawned tasks.
```
Comment (kaimast) [inline node/consensus/src/lib.rs:115]: Does it make sense to shorten this comment?

**Review by kaimast — APPROVED** [review]
Looks good to me!

File: node/consensus/src/lib.rs (hunk 2 above)
Comment (vicsn) [reply node/consensus/src/lib.rs:115]: Its a useless change, and I'm sorry for overwriting your chance. I somehow messed up during a merge conflict and was too lazy to change it back.
