### PR TITLE
Disable peer banning

### LINKED ISSUE #3999: [Bug] Some validators don't connect due to duplicate handshake attempt
## 🐛 Bug Report

Image

In the above run, the following validators lose a bunch of connections:
- val-27-44.251.223.68
- val-17-44.255.48.201

Logs below of an example validator (val-7) which won't connect. 

```
rkos_node_tcp::tcp: Received a connection from 44.251.223.68:39671                                                                                        │
rkos_node_tcp::protocols::handshake: shaking hands with 44.251.223.68:39671 as the Responder                                                              │
gateway: [MemoryPool] Received a connection request from '44.251.223.68:39671'                                                                            │
gateway: [MemoryPool] Received 'ChallengeRequest' from '44.251.223.68:39671'                                                                              │
rkos_node_tcp::protocols::handshake: handshake with 44.251.223.68:39671 failed: Duplicate handshake attempt with '44.251.223.68:5000'                     │
rkos_node_tcp::tcp: Failed to connect with 44.251.223.68:39671: Duplicate handshake attempt with '44.251.223.68:5000'                                     │
```

However, in essence there should not be a duplicate handshake attempt, this is val-17:

```
│2025-11-05T22:01:48.979063+0100 DEBUG snarkos_node_network::peering: [MemoryPool] Connecting to 16.146.100.243:5000...                                   ┤
│2025-11-05T22:01:48.979936+0100 DEBUG tcp{name="1"}: snarkos_node_tcp::protocols::handshake: shaking hands with 16.146.100.243:5000 as the Initiator     ┤
│2025-11-05T22:01:48.979942+0100 DEBUG snarkos_node_bft::gateway: [MemoryPool] Shaking hands with 16.146.100.243:5000...                                  ┤
│2025-11-05T22:01:48.980022+0100 TRACE snarkos_node_bft::gateway: [MemoryPool] Sending 'ChallengeRequest' to '16.146.100.243:5000'                        ┤
cols::handshake: handshake with 16.146.100.243:5000 failed: [MemoryPool] the peer disconnected before sending "Event::ChallengeResponse", likely due to pe┤
Unable to initiate a connection with 16.146.100.243:5000: [MemoryPool] the peer disconnected before sending "Event::ChallengeResponse", likely due to peer┤
```

Given that the peer git SHA is not even printed, the fault seems to be in `add_connecting_peer`. Maybe entries the `peer_pool` is not properly purged, or we trigger calling it twice?

Note that val-7 restarted right when it started not allowing new connections.

### PR DESCRIPTION
**Pull request by vicsn**
## Motivation

Closes https://github.com/ProvableHQ/snarkOS/issues/3999

A bunch of issues were found: https://github.com/ProvableHQ/snarkOS/issues/4000 - these are not a priority to fix at the moment.

## Test Plan

- [x] Succesful prerelease tests pass

### CODE REVIEW

File: node/sync/src/block_sync.rs [hunk 1]
```diff
@@ -1064,11 +1064,12 @@ impl<N: Network> BlockSync<N> {
         // Avoid locking `locators` and `requests` at the same time.
         drop(requests);
 
+        // TODO: Uncomment this when we have a more rigorous analysis and testing of peer banning.
         // Now remove and ban any unresponsive peers
-        for peer_ip in peers_to_ban {
-            self.remove_peer(&peer_ip);
```
Comment (ljedrz) [inline node/sync/src/block_sync.rs:1069]: This is peer removal from the sync setup, it might still be needed.

**Review by ljedrz — CHANGES_REQUESTED** [review]
Just one issue, the rest is OK.

File: node/sync/src/block_sync.rs (hunk 1 above)
Comment (vicsn) [reply node/sync/src/block_sync.rs:1069]: Whoops thx for catching: 7f346cf34

**Review by ljedrz — DISMISSED** [review]

**Review by ljedrz — APPROVED** [review]
