### PR TITLE
deserialize big block on rayon thread

### LINKED ISSUE #3315: [Bug] Malicious validator can send fake BlockResponse to block honest validators from processing messages
## 🐛 Bug Report

1. Block.Transactions limits the maximum number of transactions to 1048575 in the deserialization logic
https://github.com/AleoNet/snarkVM/blob/454d555a0ee1478dce5fa1822b64525a361b6b27/ledger/block/src/transactions/bytes.rs#L29-L32
```Rust
        // Ensure the number of transactions is within bounds.
        if num_txs as usize > Self::MAX_TRANSACTIONS {
            return Err(error("Failed to read transactions: too many transactions"));
        }
```
2. Malicious validators can construct BlockResponse messages by filling a large number of fake transactions
3. The victim's message processing logic is stuck because of the deserialization of a large number of fake transactions
https://github.com/AleoNet/snarkOS/blob/cf83035ab79907329208a7f4e35d77e8e49d0596/node/bft/src/gateway.rs#L634-L635
4. The victim's block synchronization may stop due to being stuck on deserialization, see: https://github.com/ProvableHQ/snarkOS/pull/6

## Your Environment

snarkOS Version: cf83035ab79907329208a7f4e35d77e8e49d0596

### PR DESCRIPTION
**Pull request by elderhammer**
This PR is to partially resolve https://github.com/AleoNet/snarkOS/issues/3315.

### CODE REVIEW

**Comment by vicsn** [comment]
Can't add @joske as reviewer, so tagging manually.

**Review by joske — APPROVED** [review]

**Review by ljedrz — DISMISSED** [review]

**Comment by elderhammer** [comment]
How to handle failed checks?

**Comment by vicsn** [comment]
> How to handle failed checks?

You can leave it for now, someone from Aleo Foundation will have to manually trigger CI, this is a spam prevention measure.

File: node/bft/src/gateway.rs [hunk 1]
```diff
@@ -1045,17 +1075,15 @@ impl<N: Network> Reading for Gateway<N> {
...
-                    // Disconnect from this peer.
-                    self_.disconnect(peer_ip);
-                });
-            }
+        if matches!(message, Event::BlockRequest(_) | Event::BlockResponse(_)) {
+            let self_ = self.clone();
+            // Handle BlockRequest and BlockResponse messages in a separate task to not block the
+            // inbound queue.
+            tokio::spawn(async move {
+                self_.process_message_inner(peer_addr, message).await;
```
Comment (joske) [inline node/bft/src/gateway.rs:1126]:
```suggestion
                let _ = self_.process_message_inner(peer_addr, message).await;
```

File: node/bft/src/gateway.rs [hunk 2]
```diff
@@ -955,6 +968,23 @@ impl<N: Network> Gateway<N> {
             }
         }
     }
+
+    /// Processes a message received from the network.
+    async fn process_message_inner(&self, peer_addr: SocketAddr, message: Event<N>) -> io::Result<()> {
```
Comment (ljedrz) [inline node/bft/src/gateway.rs]:
```suggestion
    async fn process_message_inner(&self, peer_addr: SocketAddr, message: Event<N>) {
```
since the body is infallible; otherwise `clippy` will lint us about it someday

**Review by ljedrz — DISMISSED** [review]
LGTM with one nit (and related adjustments it will require) and a rebase.

File: node/bft/src/gateway.rs (hunk 2 above)
Comment (elderhammer) [reply node/bft/src/gateway.rs]: Because the number of failures needs to be counted, Result is returned.
https://github.com/AleoNet/snarkOS/blob/09aa62b4b877c5e96689ba2e0c77d5fd1c69ae7c/node/tcp/src/protocols/reading.rs#L144-L147
There is a problem with my modification: placing process_message_inner in a tokio::spawn task does not return the processing result, so the number of failures cannot be counted.
```Rust
/// Processes a message received from the network.
async fn process_message(&self, peer_addr: SocketAddr, message: Self::Message) -> io::Result<()> {
    if matches!(message, Event::BlockRequest(_) | Event::BlockResponse(_)) {
        let self_ = self.clone();
        // Handle BlockRequest and BlockResponse messages in a separate task to not block the
        // inbound queue.
        tokio::spawn(async move {
            self_.process_message_inner(peer_addr, message).await;
        });
    } else {
        self.process_message_inner(peer_addr, message).await;
    }
    Ok(())
}
```

Comment (ljedrz) [reply node/bft/src/gateway.rs]: Note that due to the way we've been calling `process_message` all this time (i.e. without error "bubbling") we haven't utilized this feature; also, if `process_message_inner` is infallible, it wouldn't change anything.

Failure-handling is performed in `inbound` IIRC, and the lower-level network stack doesn't need to be involved.

Comment (elderhammer) [reply node/bft/src/gateway.rs]: Do you mean we can ignore the failure statistics for now?
I am worried that when we discover abnormal statistical data in the future, we will have to spend time to investigate.

Comment (ljedrz) [reply node/bft/src/gateway.rs]: What I'm saying is that we've never used the low-level failure statistics; `process_message` needs to return a `Result` due to the lower-level API, but it has always been infallible in snarkOS.

Comment (elderhammer) [reply node/bft/src/gateway.rs]: Ok, I get it.

File: node/bft/src/gateway.rs [hunk 3]
```diff
@@ -1045,17 +1074,15 @@ impl<N: Network> Reading for Gateway<N> {
...
-                    // Disconnect from this peer.
-                    self_.disconnect(peer_ip);
-                });
-            }
+        if matches!(message, Event::BlockRequest(_) | Event::BlockResponse(_)) {
+            let self_ = self.clone();
+            // Handle BlockRequest and BlockResponse messages in a separate task to not block the
+            // inbound queue.
+            tokio::spawn(async move {
+                let _ = self_.process_message_inner(peer_addr, message).await;
```
Comment (ljedrz) [inline node/bft/src/gateway.rs]:
```suggestion
                self_.process_message_inner(peer_addr, message).await;
```
I think this is unnecessary now.

Comment (elderhammer) [reply node/bft/src/gateway.rs]: Done.

**Review by ljedrz — APPROVED** [review]
LGTM :ok_hand:

**Comment by samir247247** [comment]
not respolvee

**Comment by vicsn** [comment]
Hi @elderhammer  apologies for the very lengthy delay, are you able to merge in `origin/staging` and resolve the conflicts? If not, I'm happy to re-open the PR and fix the conflict.

**Comment by vicsn** [comment]
@elderhammer nevermind tried my hand at conflict resolution in the github UI

**Comment by elderhammer** [comment]
> @elderhammer nevermind tried my hand at conflict resolution in the github UI

Ok, if you need any help, just let me know.

**Comment by vicsn** [comment]
@elderhammer just need a `cargo +nightly fmt` run :)

**Comment by elderhammer** [comment]
> @elderhammer just need a `cargo +nightly fmt` run :)

done.

**Review by niklaslong — COMMENTED** [review]
LGTM, this mirrors the implementation in the router 👍

**Review by niklaslong — APPROVED** [review]
