### PR TITLE
[Fix] Check certificate validity early.

### LINKED ISSUE #2935: [Bug] A malicious validator can broadcast invalid BatchCertificate or Propose that cause other validators stack overflow
# https://hackerone.com/reports/2279584

## Summary:
The `Primary` recursively fetch certificates from other peer upon receiving new `Propose` and `BatchCertificate `. Although it will check the certificate before storing into db, the check is at end of the recursion. 

A malicious validator can create fake certificate that contains other fake certificate at the same round. Then the recursion will never ends and lead to stack overflow. The call stack will be like this:

```
sync_with_certificate_from_peer
    sync_with_batch_header_from_peer
        sync_with_certificate_from_peer
             ....
```

The attacker can crash all other validator in this way.

## Steps To Reproduce:

See the commit: https://github.com/Gooong/snarkOS/commit/3e7c6866203c02dd9db225f81d794ad9d2aae146

1. Clone the repo above
2. Run ./devnet.sh
3. Wait round 5
4. Check the log and we will find some node crashed: `fatal runtime error: stack overflow`

## Proof-of-Concept (PoC)

How this bug can be exploited:

The attacker just broadcast fake certificate. This will cause all other validator continously crash and shutdown the network.

## Supporting Material/References:

See the attachment 

## Impact

Cause validators crash and shutdown the network.

## Fix suggestions:

Strictly check certificate before the recursion.

### PR DESCRIPTION
**Pull request by acoglio**
Before recursively fetching previous certificates.

Closes #2935.

Since it looks like we had working code to run the exploit, it would be good to revive it and make sure it no  longer crashes the validator.

### CODE REVIEW

**Review by kaimast — APPROVED** [review]
Looks good to me!

File: node/bft/src/primary.rs [hunk 1]
```diff
@@ -955,14 +955,53 @@ impl<N: Network> Primary<N> {
...
+        // Note that certificate.signatures() only returns the endorsing signatures, not the author's signature.
+        let mut signers: HashSet<Address<N>> =
+            certificate.signatures().map(|signature| signature.to_address()).collect();
+        signers.insert(author);
+        ensure!(
+            committee_lookback.is_quorum_threshold_reached(&signers),
+            "Certificate '{}' for round {certificate_round} does not meet quorum requirements",
+            certificate.id()
+        );
+
```
Comment (raychu86) [inline node/bft/src/primary.rs]: We should already be performing this check in the subsequent call to `sync_with_certificate_from_peer` -> `insert_certificate` -> `check_certificate`.

Why not add the following `is_committee_member` checks into `check_certificate`?

File: node/bft/src/primary.rs [hunk 2]
```diff
@@ -955,14 +955,53 @@ impl<N: Network> Primary<N> {
...
+        // Ensure that the signers of the certificate are in the committee.
+        for signer in signers {
```
Comment (raychu86) [inline node/bft/src/primary.rs]: This check can be parallelized with `cfg_iter`

File: node/bft/src/primary.rs (hunk 1 above)
Comment (acoglio) [reply node/bft/src/primary.rs]: We perform the quorum signer check in check_certificate, but that's after the recursive fetching of certificates, which is the reason why the attack in #2935 works. By performing the check before the recursive fetching, we prevent that attack. Then the same check in check_certificate becomes redundant, along with essentially all of the checks done there.

Regarding the separate check that the signers are committee members, I think we could maybe safely perform it later, but it seemed cleaner to do all the necessary checks in one place (in the code added by this commit).

Comment (raychu86) [reply node/bft/src/primary.rs]: That makes sense, but then it seems like we are doing these signature checks multiple times, which can get expensive. 

Additionally, for cleanliness, it might be better to create a helper method for these checks since they are done in multiple places.

Comment (acoglio) [reply node/bft/src/primary.rs]: Yes, we should eliminate those other checks, but I was thinking of doing that in a separate PR?

File: node/bft/src/primary.rs (hunk 2 above)
Comment (acoglio) [reply node/bft/src/primary.rs]: Done.

File: node/bft/src/primary.rs (hunk 1 above)
Comment (acoglio) [reply node/bft/src/primary.rs]: I added a `Storage::check_incoming_certificate()` method that could be used to check all incoming certificates from other validators. Certificates created by the current validator must already satisfy the checks by construction. So we should be able to eliminate several redundant checks, as net effect, compared to before. But we need to examine the callers a bit better, which is why I'm thinking that a separate PR to remove those redundant checks would be better.

**Review by raychu86 — APPROVED** [review]

**Comment by vicsn** [comment]
Asked Kai some questions in DM about testing this.

**Comment by kaimast** [comment]
Quick update: I was able to reproduce the attack. I will verify that the attack does not work anymore with the proposed changes soon.

Here are some observations I made:
1. There are already some checks in place that reject batches that contain the author as one of the endorsers. The original attack code does that because a certificate needs at least one signer. But this can be circumvented by having a random other address or a second malicious validator sign the batch. There is no way to verify the signer is valid before retrieving the full certificate chain, unless I am missing something.
2. SnarkVM also rejects batches that have timestamps too close together. The original attack set the same timestamp for all fake certificates, and correct nodes will reject these.
3. What seems to work is setting timestamps in the future. Nodes probably should reject batches that are more than a second in the future. On my branch, nodes seem to (at least initially) accept batches that are multiple minutes in the future.

File: node/bft/src/helpers/storage.rs [hunk 3]
```diff
@@ -494,6 +494,49 @@ impl<N: Network> Storage<N> {
...
+    /// It suffices to check that the signers (author and endorsers) are members of the applicable committee
+    /// and that they form a quorum in the committee.
+    /// Under the fundamental fault tolerance assumption of at most `f` (stake of) faulty validators,
+    /// the quorum check on signers guarantees that at least one correct validator
+    /// has ensured the validity of the proposal contained in the certificate,
+    /// either by construction (by the author) or by checking (by an endorser):
+    /// given `N > 0` total stake, and `f` the largest integer `< N/3` (where `/` is exact rational division),
+    /// we have `N >= 3f + 1`, which implies `N - f >= 2f + 1`, which is always `> f`;
+    /// `N - f` is the quorum stake.
+    pub fn check_incoming_certificate(&self, certificate: &BatchCertificate<N>) -> Result<()> {
```
Comment (kaimast) [inline node/bft/src/helpers/storage.rs:508]: I think we need to change the name of either this function or `check_certificate` to make it more clear which one is used when.

File: node/bft/src/helpers/storage.rs [hunk 4]
```diff
@@ -494,6 +494,49 @@ impl<N: Network> Storage<N> {
...
+        // Retrieve the committee lookback.
+        let committee_lookback = self.ledger.get_committee_lookback_for_round(certificate_round)?;
+
+        // Ensure that the signers of the certificate reach the quorum threshold.
+        // Note that certificate.signatures() only returns the endorsing signatures, not the author's signature.
+        let mut signers: HashSet<Address<N>> =
+            certificate.signatures().map(|signature| signature.to_address()).collect();
+        signers.insert(certificate_author);
+        ensure!(
+            committee_lookback.is_quorum_threshold_reached(&signers),
```
Comment (kaimast) [inline node/bft/src/helpers/storage.rs:522]: If we check the threshold here, do we still need to retrieve the`committee_lookback` in `process_batch_certificate_from_peer`?

File: node/bft/src/primary.rs [hunk 5]
```diff
@@ -955,14 +955,28 @@ impl<N: Network> Primary<N> {
             bail!("Received a batch certificate for myself ({author})");
         }
 
-        // Store the certificate, after ensuring it is valid.
+        // Ensure that the incoming certificate is valid.
+        self.storage.check_incoming_certificate(&certificate)?;
```
Comment (kaimast) [inline node/bft/src/primary.rs:959]: If the certificate is more than 100 rounds in the future, would we just fail here? Could that happen with a correct/honest peer if there is a network issue?

File: node/bft/src/helpers/storage.rs (hunk 3 above)
Comment (kaimast) [inline node/bft/src/helpers/storage.rs:508]: I also think we should test the attack and, ideally, add some other unit tests to this function.

If you want, I can try to write a unit test from the attack code I have and push it to this branch.

**Review by kaimast — CHANGES_REQUESTED** [review]
I could verify the fix works (yay!), but, now that I have a better understanding of the code, I also left a few more notes on the PR.

To verify, this is the error message I get when honest nodes receive the attack: 
```
Cannot store a certificate from '127.0.0.1:5004' - Certificate '2671926863586933361463317741031072687577528356414354042732451240158089381291field' for round 5 does not meet quorum requirements
```

Another thing we should consider, not in this PR but sometime in the future, is removing the recursion entirely, because there could still be valid cases where you receive a fairly long certificate chain. Alternatively, we could ensure that the number of recursions always stays below some small bound.
For example, it might be more elegant to have a data structure that maps certificate ID to unprocessed certificates that depend on it. Whenever we accept a batch, we check that mapping for certificates to process next.

File: node/bft/src/primary.rs [hunk 6]
```diff
@@ -955,14 +955,28 @@ impl<N: Network> Primary<N> {
...
+        // The following call recursively fetches and stores
+        // the previous certificates referenced from this certificate.
+        // It is critical to make the following call this after validating the certificate above.
+        // The reason is that a sequence of malformed certificates,
+        // with references to previous certificates with non-decreasing rounds,
+        // cause the recursive fetching of certificates to crash the validator due to resource exhaustion.
+        // Note that if the following call, if not returning an error, guarantees the backward closure of the DAG
+        // (i.e. that all the referenced previous certificates are in the DAG before storing this one),
+        // then all the validity checks in [`Storage::check_certificate`] should be redundant.
+        // TODO: eliminate those redundant checks
```
Comment (kaimast) [inline node/bft/src/primary.rs:971]: Are we removing the redundant checks in another PR?

**Comment by acoglio** [comment]
> To verify, this is the error message I get when honest nodes receive the attack:
> 
> ```
> Cannot store a certificate from '127.0.0.1:5004' - Certificate '2671926863586933361463317741031072687577528356414354042732451240158089381291field' for round 5 does not meet quorum requirements
> ```

Nice! That's indeed the error I was expecting to happen: the certificate doesn't have enough signatures. Under the correct super-majority assumption, the validator would be unable to obtain enough signatures.

File: node/bft/src/helpers/storage.rs (hunk 3 above)
Comment (acoglio) [reply node/bft/src/helpers/storage.rs:508]: I agree that we should change the names. I was thinking that we could do that as we refactor and simplify the certificate checks in subsequent PRs.

File: node/bft/src/helpers/storage.rs (hunk 4 above)
Comment (acoglio) [reply node/bft/src/helpers/storage.rs:522]: `process_batch_certificate` from peer uses the committee for a different purpose, namely deciding whether to advance the round.

File: node/bft/src/primary.rs (hunk 5 above)
Comment (acoglio) [reply node/bft/src/primary.rs:959]: Yes, we would fail because the validator would be unable to calculate the active committee for the certificate's round, given that its blockchain is too behind compared to the round. This ties in with more general liveness issues, which need further study.

File: node/bft/src/helpers/storage.rs (hunk 3 above)
Comment (acoglio) [reply node/bft/src/helpers/storage.rs:508]: That would be great, if you are willing to do that.

File: node/bft/src/primary.rs (hunk 6 above)
Comment (acoglio) [reply node/bft/src/primary.rs:971]: Yes, there are currently several redundant checks (not just this one), and they are a bit complicated (I documented them in the code notes doc), so my thinking was to tackle those in a series of PRs each of which makes a very simple change that is easy to evaluate.

File: node/bft/src/helpers/storage.rs (hunk 3 above)
Comment (kaimast) [reply node/bft/src/helpers/storage.rs:508]: I am looking into this now, but it might require adding some code to snarkVM to generate test certificates that have valid (not just random) signatures.

**Comment by kaimast** [comment]
I have a branch [here](https://github.com/acoglio/snarkOS/compare/fix-cert-fetch...kaimast:snarkOS:fix-cert-fetch) that adds unit tests, but it requires [a small change](https://github.com/ProvableHQ/snarkVM/pull/2665) to snarkVM. 

We could merge this PR now and I will add the tests with another PR. I tested it extensively, and it should land in staging sooner than later, considering it prevents a possible attack.
