### PR TITLE
 [Fix] Guard recursive certificate fetching with is_synced check.

### LINKED ISSUE #3293: [Bug] Sync status incorrectly reported
## 🐛 Bug Report
`snarkos_bft_is_synced` metric always reports 0. It appears its criteria to be considered synced is either too strict or flawed. 

I confirmed with client and validator operators on canary net that they also see this issue. 

## Steps to Reproduce

Based on slack threads, any client or validator will see their node as not synced. 

## Expected Behavior

Once the node is synced, or within certain block time of current time the node should report itself as synced. 

## Your Environment

- mainnet-staging (`81ca9cf6f923dc8955347b0993beebeaa17161fc`)
- v1.66+
- Ubuntu 22

### PR DESCRIPTION
**Pull request by vicsn**
## Motivation

Reintroduces https://github.com/AleoNet/snarkOS/pull/3256
Which was reverted.
[CI passed here.](https://app.circleci.com/pipelines/github/ProvableHQ/snarkOS/13303/workflows/e7f49124-79d0-4282-a159-c3a63026631e)

Closes https://github.com/AleoNet/snarkOS/issues/3293

### CODE REVIEW

File: node/bft/src/primary.rs [hunk 1]
```diff
@@ -2070,13 +2087,48 @@ mod tests {
 
         // The author must be known to resolver to pass propose checks.
         primary.gateway.resolver().insert_peer(peer_ip, peer_ip, peer_account.1.address());
+        // The primary must be considered synced.
+        primary.sync.block_sync().try_block_sync(&primary.gateway.clone()).await;
```
Comment (gluax) [inline node/bft/src/primary.rs:2091]: NIT: Tests should be moved to a different file. Otherwise, it's unclear if this line of code was in a test. Commenting since I would have left a comment about the fact that we are taking a reference to a `clone`, i.e, the `clone` is pointless.

**Review by gluax — APPROVED** [review]

**Review by evanmarshall — APPROVED** [review]
lgtm

**Review by Meshiest — APPROVED** [review]

File: node/bft/src/primary.rs (hunk 1 above)
Comment (vicsn) [reply node/bft/src/primary.rs:2091]: I think that's a subjective decision which won't go out of this code anytime soon. Fortunately Github indicates `mod tests {` in the blue-grey summary line just above.
