### PR TITLE
[fix] CLI error handling message

### LINKED ISSUE #3286: [Bug] Give a proper error message when developer execute fails
## Steps to Reproduce

1. Start a snarkOS network with network 1
2. Call snarkos developer execute with any other network (e.g. the default 0)
3. It returns an empty non-descriptive error: :warning:

## Expected Behavior

The returned error message should be clear.
Please also investigate other potential errors.

### PR DESCRIPTION
**Pull request by joske**
Fixes https://github.com/AleoNet/snarkOS/issues/3286

Now prints the following:
```
cargo run -- developer execute  --private-key APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH --query "http://0.0.0.0:3030" --broadcast "http://0.0.0.0:3030/mainnet/transaction/broadcast" credits.aleo transfer_public
   Compiling snarkos-cli v2.2.7 (/home/jos/Projects/snarkOS/cli)
   Compiling snarkos v2.2.7 (/home/jos/Projects/snarkOS)
    Finished dev [optimized] target(s) in 11.03s
     Running `target/debug/snarkos developer execute --private-key APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH --query 'http://0.0.0.0:3030' --broadcast 'http://0.0.0.0:3030/mainnet/transaction/broadcast' credits.aleo transfer_public`

📦 Creating execution transaction for 'credits.aleo/transfer_public'...

⚠️  Failed to fetch program credits.aleo: Response[status: 404, status_text: Not Found, url: http://0.0.0.0:3030/mainnet/program/credits.aleo]
```

### CODE REVIEW

File: cli/src/commands/developer/mod.rs [hunk 1]
```diff
@@ -131,7 +131,9 @@ impl Developer {
             Ok(response) => response.into_json().map_err(|err| err.into()),
             Err(err) => match err {
                 ureq::Error::Status(_status, response) => {
-                    bail!(response.into_string().unwrap_or("Response too large!".to_owned()))
+                    // Response::into_string() returns the response BODY, but there is none
+                    // better to format using debug this at least gives some useful info
+                    bail!("Failed to fetch program {program_id}: {response:?}")
```
Comment (raychu86) [inline cli/src/commands/developer/mod.rs]:
```suggestion
                    // Debug formatting displays more useful info, especially if the response body is empty.
                    bail!("Failed to fetch program {program_id}: {response:?}")
```

**Review by raychu86 — CHANGES_REQUESTED** [review]

File: cli/src/commands/developer/mod.rs (hunk 1 above)
Comment (raychu86) [reply cli/src/commands/developer/mod.rs]: @joske Could you apply these changes? I don't have push access to your fork so I can't do it myself

**Review by raychu86 — APPROVED** [review]
