### PR TITLE
[Fix] Correct downgrade_peer_to_candidate for non-Gateway use

### LINKED ISSUE #3944: [Bug] Validators fail to handshake
## 🐛 Bug Report

After resetting a quorum minority of validators, they can't connect anymore:

Logs from 35.91.187.250: 

```
 [MemoryPool] Dropping '44.252.71.171:5000' for being already connected (aleo1p9sg8gapg22p3j42tang7c8kqzp4lhe6mg77gx32yys2a5y7pq9s│
 [MemoryPool] Sending 'Disconnect' to '44.252.71.171:5000'                                                                        │
e_tcp::protocols::handshake: handshake with 44.252.71.171:5000 failed: Dropped '44.252.71.171:5000' for reason: ProtocolViolation │
e_tcp::tcp: Unable to initiate a connection with 44.252.71.171:5000: Dropped '44.252.71.171:5000' for reason: ProtocolViolation   │
ryPool] Unable to connect to '44.252.71.171:5000' - I/O error: Dropped '44.252.71.171:5000' for reason: ProtocolViolation         │
```

Logs from 44.252.71.171 (at a completely different time, just to illustrate):
```
e_tcp::protocols::handshake: shaking hands with 35.91.187.250:49313 as the Responder                                              │
 [MemoryPool] Received a connection request from '35.91.187.250:49313'                                                            │
 [MemoryPool] Received 'ChallengeRequest' from '35.91.187.250:49313'                                                              │
d to load bootstrap peers from environment: environment variable not found                                                        │
 [MemoryPool] Sending 'ChallengeResponse' to '35.91.187.250:49313'                                                                │
 [MemoryPool] Sending 'ChallengeRequest' to '35.91.187.250:49313'                                                                 │
e_tcp::protocols::handshake: handshake with 35.91.187.250:49313 failed: [MemoryPool] '35.91.187.250:49313' disconnected: Disconnec│
e_tcp::tcp: Failed to connect with 35.91.187.250:49313: [MemoryPool] '35.91.187.250:49313' disconnected: Disconnect { reason: Prot│
```

CC @meddle0x53 who found the bug

### PR DESCRIPTION
**Pull request by ljedrz**
When we abort a validator handshake attempt due to already being connected to the given Aleo address, we should neither error out (because it's not an error), nor we should downgrade any peer that's not a `ConnectingPeer` (which is the intended downgrade target) on a broken handshake. This could only happen to a validator due to that extra handshake condition, but we should apply this to other nodes too as a means of future-proofing.

Fixes https://github.com/ProvableHQ/snarkOS/issues/3944.

### CODE REVIEW

File: node/bft/src/gateway.rs [hunk 1]
```diff
@@ -1375,7 +1378,12 @@ impl<N: Network> Gateway<N> {
         // Verify the challenge request. If a disconnect reason was returned, send the disconnect message and abort.
         if let Some(reason) = self.verify_challenge_request(peer_addr, &peer_request) {
             send_event(&mut framed, peer_addr, reason.into()).await?;
-            return Err(error(format!("Dropped '{peer_addr}' for reason: {reason:?}")));
+            if reason == DisconnectReason::NoReasonGiven {
```
Comment (vicsn) [inline node/bft/src/gateway.rs:1381]: Is this really one to one to already being connected?

**Review by vicsn — APPROVED** [review]
