### PR TITLE
[Fix] Fix flaky connection cleanup case

### LINKED ISSUE #3190: [Bug] test_connection_cleanups is flaky
## 🐛 Bug Report

It appears that sometimes, when a validator is picked in the test, it fails:
```
thread 'test_connection_cleanups' panicked at node/router/tests/cleanups.rs:74:9:
the deadline has elapsed for condition: tcp0.num_connected() == 1 && tcp1.num_connected() == 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

A quick print statement indicated: `Unable to connect to '127.0.0.1:63168' - '127.0.0.1:63168' disconnected before sending "Message::ChallengeResponse"`

## Steps to Reproduce

`cd node/router && cargo test test_connection_cleanups`

Due to random sampling of the node type, the test only sometimes fails.

## Expected Behavior

The test should pass.

## Your Environment

Ran it on `mainnet-staging` `491f3078a`

### PR DESCRIPTION
**Pull request by niklaslong**
Stricter peering rules were introduced in https://github.com/AleoHQ/snarkOS/pull/3163 which caused connections to fail if peers were not in the validator's trusted peer set (which we are not setting in these cases). Relaxing the requirements in this particular case should fix the flakiness. 

Closes #3190.

### CODE REVIEW

**Review by howardwu — APPROVED** [review]

File: node/router/tests/common/mod.rs [hunk 1]
```diff
@@ -111,7 +111,7 @@ pub async fn validator(listening_port: u16, max_peers: u16) -> TestRouter<Curren
         sample_account(),
         &[],
         max_peers,
-        false,
+        true,
```
Comment (vicsn) [inline node/router/tests/common/mod.rs]: Thank you!!

The default for validators is false, so I suggest to add a comment, same as https://github.com/AleoHQ/snarkOS/pull/3163/files#diff-0490634f09b53b897acaf1041eb100043b7bd7627128eb7e77f745df58b64377R62

```suggestion
        true, // This test requires validators to connect to peers.
```

**Review by vicsn — APPROVED** [review]
One nit

**Review by joske — APPROVED** [review]
