### PR TITLE
Delay the promotion of the peer from connecting to connected

### LINKED ISSUE #3331: [Bug] Abnormal disconnection caused by asynchronous Ping message
## Steps to Reproduce

1.Receive a Pong message from the peer and create an asynchronous task to send a Ping message to the peer after PING_SLEEP_IN_SECS seconds.
```
2024-06-25T07:25:55.802800Z TRACE snarkos_node_router::inbound: Received 'Pong' from '127.0.0.1:4132'
```
https://github.com/AleoNet/snarkOS/blob/09aa62b4b877c5e96689ba2e0c77d5fd1c69ae7c/node/src/client/router.rs#L248-L266
2.Periodic refresh of peers.
```
2024-06-25T07:26:07.870256Z  INFO snarkos_node_router::heartbeat: Disconnecting from '127.0.0.1:4132' (periodic refresh of peers)
2024-06-25T07:26:07.870268Z TRACE snarkos_node_router::outbound: Sending 'Disconnect' to '127.0.0.1:4132'
```
3.Receive a connection request from a peer
```
2024-06-25T07:26:15.775172Z DEBUG tcp{name="0"}: snarkos_node_tcp::tcp: Received a connection from 127.0.0.1:51296
```
4.Complete the handshake, and add the peer to the router.
```
2024-06-25T07:26:15.775550Z DEBUG tcp{name="0"}: snarkos_node_tcp::protocols::handshake: shaking hands with 127.0.0.1:51296 as the Responder
2024-06-25T07:26:15.775572Z DEBUG snarkos_node_router::handshake: Received a connection request from '127.0.0.1:51296'
2024-06-25T07:26:15.789750Z TRACE snarkos_node_router::handshake: Received 'ChallengeRequest' from '127.0.0.1:51296'
2024-06-25T07:26:15.790940Z TRACE snarkos_node_router::handshake: Sending 'ChallengeResponse' to '127.0.0.1:51296'
2024-06-25T07:26:15.791066Z TRACE snarkos_node_router::handshake: Sending 'ChallengeRequest' to '127.0.0.1:51296'
2024-06-25T07:26:15.801582Z TRACE snarkos_node_router::handshake: Received 'ChallengeResponse' from '127.0.0.1:51296'
2024-06-25T07:26:15.804149Z DEBUG tcp{name="0"}: snarkos_node_tcp::protocols::handshake: successfully handshaken with 127.0.0.1:51296
```
https://github.com/AleoNet/snarkOS/blob/09aa62b4b877c5e96689ba2e0c77d5fd1c69ae7c/node/router/src/handshake.rs#L275-L276
5.Create asynchronous tasks for processing, reading, and writing
```
2024-06-25T07:26:15.804489Z TRACE tcp{name="0"}: snarkos_node_tcp::protocols::reading: spawned a task for processing messages from 127.0.0.1:51296
```
6.Asynchronous task sleep ends, send Ping message
```
2024-06-25T07:26:15.804961Z TRACE snarkos_node_router::outbound: Sending 'Ping' to '127.0.0.1:4132'
```
7.Because the peer has been added to the router, can_send returns true and the Ping message is sent. However, because the writing asynchronous task has not been created, the sending fails.
```
2024-06-25T07:26:15.804980Z  WARN snarkos_node_router::outbound: Failed to send 'Ping' to '127.0.0.1:4132': not connected
2024-06-25T07:26:15.804988Z DEBUG snarkos_node_router::outbound: Disconnecting from '127.0.0.1:4132' (unable to send)
2024-06-25T07:26:15.805060Z  WARN tcp{name="0"}: snarkos_node_tcp::tcp: Failed to disconnect, was not connected to 127.0.0.1:51296
2024-06-25T07:26:15.805072Z  WARN snarkos_node_router: Disconnecting with fallback safety (report this to @ljedrz)
```
https://github.com/AleoNet/snarkOS/blob/09aa62b4b877c5e96689ba2e0c77d5fd1c69ae7c/node/router/src/outbound.rs#L48-L59
8.The reading and writing asynchronous tasks are created later.
```
2024-06-25T07:26:15.805089Z TRACE tcp{name="0"}: snarkos_node_tcp::protocols::reading: spawned a task for reading messages from 127.0.0.1:51296
2024-06-25T07:26:15.805254Z TRACE tcp{name="0"}: snarkos_node_tcp::protocols::writing: spawned a task for writing messages to 127.0.0.1:51296
```

This will cause two problems:
- Asynchronous tasks such as processing, reading, and writing are not terminated correctly
- Because the peer believes that the connection is complete, it will reject subsequent connections from the current node
```
2024-06-25T07:26:32.872315Z DEBUG tcp{name="1"}: snarkos_node_tcp::tcp: Received a connection from 127.0.0.1:57797
2024-06-25T07:26:32.872716Z DEBUG tcp{name="1"}: snarkos_node_tcp::protocols::handshake: shaking hands with 127.0.0.1:57797 as the Responder
2024-06-25T07:26:32.872755Z DEBUG snarkos_node_router::handshake: Received a connection request from '127.0.0.1:57797'
2024-06-25T07:26:32.873158Z TRACE snarkos_node_router::handshake: Received 'ChallengeRequest' from '127.0.0.1:57797'
2024-06-25T07:26:32.873211Z ERROR tcp{name="1"}: snarkos_node_tcp::protocols::handshake: handshake with 127.0.0.1:57797 failed: Dropping connection request from '127.0.0.1:4202' (already connected)
2024-06-25T07:26:32.873252Z ERROR tcp{name="1"}: snarkos_node_tcp::tcp: Failed to connect with 127.0.0.1:57797: Dropping connection request from '127.0.0.1:4202' (already connected)
```

## Expected Behavior
This shouldn't happen

## Your Environment
snarkOS Version: 09aa62b4b877c5e96689ba2e0c77d5fd1c69ae7c

### PR DESCRIPTION
**Pull request by ljedrz**
A re-opening of https://github.com/AleoNet/snarkOS/pull/2690; there is also https://github.com/AleoNet/snarkOS/pull/2729 which I had considered to be a simpler alternative, but I believe that both changes are desirable (with this one going in first) for a more foolproof setup.

The Aleo network stack is two-tiered, and both the lower- and higher-level layers recognize that connections may have been started but not fully finalized yet, which corresponds to the "connecting" and "connected" states of connections and peers respectively.

This PR ensures that the lower networking layer is the first one to conclude its connection setup, which is done by marking the (higher-level) peers as "connected" only via `OnConnect`, which is triggered only after the lower-level layer has concluded all its work. To do this, the `Peer` object (instead of just the address) is persisted in the `connecting_peers` collection past the handshake, and moved to `connected_peers` only during `OnConnect::on_connect`.

The existing tests are adjusted to account for this; I've also tested it locally in a `--dev` network.

Fixes https://github.com/AleoNet/snarkOS/issues/3331 and all other potential issues of its kind (i.e. attempting to treat a connection as fully established before the lower-level TCP stack recognizes it as such).

### CODE REVIEW

File: node/router/src/handshake.rs [hunk 1]
```diff
@@ -107,9 +107,11 @@ impl<N: Network> Router<N> {
...
-        // Remove the address from the collection of connecting peers (if the handshake got to the point where it's known).
         if let Some(ip) = peer_ip {
-            self.connecting_peers.lock().remove(&ip);
+            if handshake_result.is_err() {
+                // Remove the address from the collection of connecting peers (if the handshake got to the point where it's known).
+                self.connecting_peers.lock().remove(&ip);
+            }
         }
 
         // If the handshake succeeded, announce it.
```
Comment (niklaslong) [inline node/router/src/handshake.rs]: Can't comment below for some reason (outside the diff maybe?) but I think we can remove this log here?

**Review by niklaslong — APPROVED** [review]

**Comment by vicsn** [comment]
Superseded by https://github.com/AleoNet/snarkOS/pull/3418 to resolve `cargo fmt` related merge conflicts.

**Comment by vicsn** [comment]
NOTE: this was not actually merged, must be a bug in Github since the branchname is the same as the superseding PR.
