### PR TITLE
[HackerOne-2310746] Add fee check to transmissions fetched in batch proposal.

### LINKED ISSUE #2990: [Bug] A malicious validator can broadcast certificate with `Transaction::Fee` and block the network
# https://hackerone.com/reports/2310746

## Summary:

Currently, Aleo does not speculate on `Transaction::Fee`:

```
                    // There are no finalize operations here.
                    // Note: This will abort the entire atomic batch.
                    Transaction::Fee(..) => Err("Cannot speculate on a fee transaction".to_string()),
```

However, malicious can propose a `BatchPropose` with `Fee` transaction. Other validators won't check if a `BatchPropose` contains a `Fee` transaction and will sign the proposal. Once the `Certificate` with `Fee` transaction is committed, it will block the execution of the block. All the validators will be blocked.

## Steps To Reproduce:

1. Clone snarkOS
2. Checkout testnet3: `git checkout 052457bddbf736f88227c543646890f8588a0efb`
3. Apply the patch unchecked_fee_transaction.patch in the attachment: `git apply unchecked_fee_transaction.patch`
4. Run ./devnet.sh (To make it easy to reproduce, run all 4 validators with the patch)
5. Wait some round and find the network stuck:
image

Also see the attached sample log `sample_log.zip`
[sample_log.zip](https://github.com/AleoHQ/snarkOS/files/13897085/sample_log.zip)

## Proof-of-Concept (PoC)

See above

## Fix Suggestions:

Check if a `BatchPropose` contains `Transaction::Fee` before signing.

## Impact

A malicious validator can broadcast certificate with `Transaction::Fee` and block the whole network

### PR DESCRIPTION
**Pull request by raychu86**
## Motivation

This PR performs basic checks on transmissions fetched from batch proposals. We now check that the transmission id's match and that the transmission is not a `Fee` transaction. 

This fix does not address all the issues, but is an added mitigation for the malicious Fee transmission case. This is an incremental fix for #3098.

## Related PRs

This PR is related to #3098, and is a simpler approach that addresses one case of the problem.

This PR fixes #2990, but is insufficient for #2991.

### CODE REVIEW

**Review by howardwu — APPROVED** [review]

File: node/bft/src/primary.rs [hunk 1]
```diff
@@ -569,7 +569,16 @@ impl<N: Network> Primary<N> {
         }
 
         // If the peer is ahead, use the batch header to sync up to the peer.
-        let transmissions = self.sync_with_batch_header_from_peer(peer_ip, &batch_header).await?;
+        let mut transmissions = self.sync_with_batch_header_from_peer(peer_ip, &batch_header).await?;
+
+        // Check that the transmission ids match and are not fee transactions.
+        for (transmission_id, transmission) in transmissions.iter_mut() {
```
Comment (howardwu) [inline node/bft/src/primary.rs:575]: @ljedrz can you profile this and determine if an optimization is possible with rayon or tokio?

Comment (howardwu) [reply node/bft/src/primary.rs:575]: Feel free to open a new PR if so

Comment (raychu86) [reply node/bft/src/primary.rs:575]: Note that the number of transmissions here can be up to 50, and each one will be deserializing the Transmission Data object.
