### PR TITLE
[Fix] Use correct edition when recursively fetching programs

### LINKED ISSUE #3758: [Bug] `snarkos developer execute` doesn't work under consensus V8
## 🐛 Bug Report

The cli command only inserts the programs used once, and those programs are added as edition 0 to the VM stack because it's the first program initialization with an empty VM. However after consensus V8 it's not possible to execute programs in edition 0, thus all executions will fail locally.

This applies to any program besides `credits.aleo`.

## Steps to Reproduce

Execute a program other than `credits.aleo` with `snarkos developer execute`.

## Expected Behavior

The command should deal with the edition restriction.

## Your Environment

- v4.0.1

### PR DESCRIPTION
**Pull request by kaimast**
This PR replaces #4002 and fixes #3758.

### Changes
* [83757e8](https://github.com/ProvableHQ/snarkOS/pull/4037/commits/83757e887b8bf2f9cef5fb91fea3b030e0082e27) ensure the correct edition for each import is fetched. The current behavior only fetches the latest edition for the top-level program and then incorrectly reuses that value.
*  [c74b12d](https://github.com/ProvableHQ/snarkOS/pull/4037/commits/c74b12d9e240d242a08c56c5e6c4b10314b49d4e) improves a doc comment.
* [7ba6481](https://github.com/ProvableHQ/snarkOS/pull/4037/commits/7ba6481aee92e2764c1fba54748c0df92e2aa576) changes the default endpoint/base_url to `https://api.explorer.provable.com/v2/`. The `v2` component is needed (otherwise the explorer returns a 404 error) and refers to the explorer version, not the snarkOS API version.
* [2db8047](https://github.com/ProvableHQ/snarkOS/pull/4037/commits/2db8047e32ca9b93728a1039d55f0ad12100d0b0) adds a new flag `--skip-funds-check`, so you can test these changes without requiring actual funds in your account. This flag is only intended for testing purposes and marked as hidden.

### Testing
Ensure the following works to verify the correctness of these changes:
```
~> snarkos developer execute --private-key APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH \
    token_registry.aleo transfer_public 1field \
    aleo1rhgdu77hgyqd3xjj8ucu3jj9r2krwz6mnzyd80gncr5fxcwlh5rsvzp9px 1000u128 \
    --broadcast https://api.explorer.provable.com/v1/mainnet/transaction/broadcast --skip-funds-check

📦 Creating execution transaction for 'token_registry.aleo/transfer_public'...
✅ Created execution transaction for 'token_registry.aleo/transfer_public'
⌛ Execution at1n73ffv5eewcnkfkfd7acyyaslnwvrjnewygu9wxudufev4veeqyq2juge7 ('token_registry.aleo/transfer_public') has been broadcast to https://api.explorer.provable.com/v1/mainnet/transaction/broadcast.
at1n73ffv5eewcnkfkfd7acyyaslnwvrjnewygu9wxudufev4veeqyq2juge7```

### CODE REVIEW

File: cli/src/commands/developer/execute.rs [hunk 1]
```diff
@@ -122,7 +127,7 @@ impl Execute {
         // Specify the query
         let query = Query::<N, BlockMemory<N>>::from(endpoint.clone());
 
-        // TODO (kaimast): can this ever be true?
+        // Check if the query is a static query.
```
Comment (kaimast) [inline cli/src/commands/developer/execute.rs:130]: I left the node because we instantiate the query as a `RestQuery` in the previous line.

Do we support passing a static query as an endpoint here? I never tested this and am unsure if it works.

Comment (vicsn) [reply cli/src/commands/developer/execute.rs:130]: It works, but the variable naming needs to be cleaned up one day.

**Review by vicsn — APPROVED** [review]
LGTM!
