### PR TITLE
Read the node's private key from the filesystem

### LINKED ISSUE #1583: [Bug] password should be passed from a file
## 🐛 Bug Report

The password is read from a value in the config or command line, it should be read from a file. This way you can pass it to a systemd service from load credentials or to docker from docker secrets. (usually secrets should be read from files).

I would be happy to make a Proposal PR if you are open to the change.

(I filed it as a bug because this is potentially a security risk, let me know if you want to classify it differently)

### LINKED ISSUE #2169: [Proposal] entering private key in plaintext raise concerns
## 💥 Proposal

Entering private key in plaintext in terminal and yields potential threats, instead a signature derived from private key file would be much more secure I suppose.

### PR DESCRIPTION
**Pull request by ljedrz**
This PR is a proposal to address the community requests to allow the node's private key to be loaded from the filesystem in addition to being passed as a runtime argument or input from the command line.

The main change is as follows:
```sh
# Using a private key string
--beacon --private-key "{private_key_string}"
--validator --private-key "{private_key_string}"
--prover --private-key "{private_key_string}"
--client --private-key "{private_key_string}"

# Using a private key file
--beacon --private-key-file "{file_path}"
--validator --private-key-file "{file_path}"
--prover --private-key-file "{file_path}"
--client --private-key-file "{file_path}"
```

This setup, while a bit more verbose, provides better optionality for the user.

### CODE REVIEW

**Review by joske — APPROVED** [review]

**Review by niklaslong — APPROVED** [review]

**Comment by howardwu** [comment]
^This was Github. Sorry, I don't know why these "auto-closes" keep happening. In snarkVM, the branches usually retarget, rather than closing.

**Comment by ljedrz** [comment]
Updated the PR to maintain the current node type parameter setup; with the new changes, the nodes should be started with:
```
--beacon --private-key <PRIVATE_KEY>
```
or
```
--validator --private-key-path <PATH>
```
That way the private key can be provided directly (as before) or from the filesystem.

File: cli/src/commands/start.rs [hunk 1]
```diff
@@ -45,18 +45,25 @@ pub struct Start {
...
+    pub prover: bool,
+    /// Specify this node as a client
     #[clap(long = "client")]
-    pub client: Option<String>,
+    pub client: bool,
+
+    /// Specify the node's account private key.
+    #[clap(long = "private-key")]
+    pub private_key: Option<String>,
+    /// Specify the path to the node's account private key.
```
Comment (howardwu) [inline cli/src/commands/start.rs]: We may want to provide more clarity to the user that this is the `file path` and perhaps the `absolute file path` (or relative if that is the case)

File: cli/src/commands/start.rs [hunk 2]
```diff
@@ -45,18 +45,25 @@ pub struct Start {
...
+    #[clap(long = "private-key-path")]
+    pub private_key_path: Option<PathBuf>,
```
Comment (howardwu) [inline cli/src/commands/start.rs]: nit: perhaps we rename this to `private-key-file` for more clarify? (as a `path` can denote a `file` or `folder`)

File: cli/src/commands/start.rs [hunk 3]
```diff
@@ -160,6 +168,29 @@ impl Start {
         }
     }
 
+    /// Read the private key directly from an argument or from a filesystem location.
+    fn parse_private_key(&mut self) -> Result<()> {
```
Comment (howardwu) [inline cli/src/commands/start.rs:172]: We should add a check that both cannot be provided:
For example:
```rs
// Ensure only one private key flag is provided to the CLI.
if self.private_key.is_some() && self.private_key_path.is_some() {
    bail!("Both the private key string and file path flags were specified, please pick only one")
}
```

**Comment by howardwu** [comment]
We can also make the `--private-key*` variants optional on the `--dev` mode commands.

**Comment by howardwu** [comment]
We should also forbid `--private-key ""` since the flag itself is optional now.

**Comment by ljedrz** [comment]
> We can also make the --private-key* variants optional on the --dev mode commands.

This is already the case; `--dev` runs can omit those params, in which case a random key is sampled.

> We should also forbid --private-key "" since the flag itself is optional now.

Done in https://github.com/AleoHQ/snarkOS/pull/2465.
